Test: CheckMisa
Target: verilator_target
--------------------------------[ Traceback ]---------------------------------
Traceback (most recent call last):
  File "/home/hoangdang/Documents/git_clone/riscv-tests/debug/testlib.py", line 1389, in run
    self.classSetup()
  File "/home/hoangdang/Documents/git_clone/riscv-tests/debug/testlib.py", line 1445, in classSetup
    BaseTest.classSetup(self)
  File "/home/hoangdang/Documents/git_clone/riscv-tests/debug/testlib.py", line 1352, in classSetup
    self.target_process = self.target.create()
  File "/home/hoangdang/Documents/git_clone/riscv-tests/debug/targets/RISC-V/verilator_target.py", line 57, in create
    return testlib.Openocd(
TypeError: Openocd.__init__() got an unexpected keyword argument 'logname'
-------------------------------[ End of logs ]--------------------------------
Result: exception
Logfile: logs/20250603-143204-verilator_target-CheckMisa.log
Reproduce: ./gdbserver.py targets/RISC-V/verilator_target.py CheckMisa
Time elapsed: 0.00s
